# build stage
FROM node:erbium as build-stage
WORKDIR /app
COPY wa-admin/package*.json ./
RUN npm install
COPY wa-admin/ .
RUN npm run build --prod

# production stage
FROM abiosoft/caddy:1.0.3-no-stats as production-stage
COPY docker/wa-admin/config/Caddyfile /etc/Caddyfile
COPY --from=build-stage /app/dist/wa-admin /srv
COPY docker/wa-admin/config/appConfig.json /srv/appConfig.json
