# build stage
FROM node:erbium as build-stage
WORKDIR /app
COPY wa-public/package*.json ./
RUN npm install
COPY wa-public/ .
RUN npm run build --prod

# production stage
FROM abiosoft/caddy:1.0.3-no-stats as production-stage
COPY docker/wa-public/config/Caddyfile /etc/Caddyfile
COPY --from=build-stage /app/dist/wa-public /srv
COPY docker/wa-public/config/config.json /srv/assets/config/config.json
